Vagrant.configure(2) do |config|
  config.vm.box = "mrh1997/vanilla-win7-32bit"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 3
  end

  config.vm.provision "shell", inline: <<-SHELL
    choco install visualstudioexpress2013windowsdesktop -y
    choco install vs2013.4 -y
    choco install python2-x86_32 -y
    choco install cmake -y
    choco install git -y
    choco install gnuwin32-coreutils.install -y
  SHELL
end
